import { z } from "zod";
import { prisma } from "@/lib/db";
import { DEFAULT_SITE_CONFIG, mergeSiteConfigWithDefaults } from "@/lib/site-content";

const textItemSchema = z.object({
  title: z.string(),
  description: z.string(),
});

const faqItemSchema = z.object({
  question: z.string(),
  answer: z.string(),
});

const siteConfigSchema = z.object({
  global: z.object({
    name: z.string(),
    shortName: z.string(),
    teacherName: z.string(),
    teacherDisplayName: z.string(),
    companyName: z.string(),
    supportEmail: z.string(),
    slogan: z.string(),
    logo: z.string(),
    shareImage: z.string(),
    siteTitle: z.string(),
    siteDescription: z.string(),
    ogTitle: z.string(),
    ogDescription: z.string(),
    navHomeLabel: z.string(),
    navCoursesLabel: z.string(),
    navAboutLabel: z.string(),
    navMyCoursesLabel: z.string(),
    loginCtaLabel: z.string(),
    mainCourseSlug: z.string(),
    regularPriceCents: z.number(),
    ageRange: z.string(),
    serviceModel: z.string(),
    loginEyebrow: z.string(),
    loginTitle: z.string(),
    loginHint: z.string(),
    purchaseHint: z.string(),
    orderHelpText: z.string(),
    myCoursesIntro: z.string(),
    myCoursesEmpty: z.string(),
    myCoursesTitle: z.string(),
    orderSectionTitle: z.string(),
    continueLearningLabel: z.string(),
    continuePayingLabel: z.string(),
    orderClosedLabel: z.string(),
    logoutLabel: z.string(),
    currencyPrefix: z.string(),
    courseCardCtaLabel: z.string(),
    courseCoverAltText: z.string(),
    lessonCountUnitLabel: z.string(),
    validityLabelPrefix: z.string(),
    courseCardRegularPriceUnit: z.string(),
    purchasePaymentLabel: z.string(),
    purchaseLoadingLabel: z.string(),
    purchaseSignedInLabel: z.string(),
    purchaseSignedOutLabel: z.string(),
    genericRequestError: z.string(),
    createOrderError: z.string(),
    loginSuccessText: z.string(),
    registerSuccessText: z.string(),
    loginErrorText: z.string(),
    phoneLabel: z.string(),
    phonePlaceholder: z.string(),
    passwordLabel: z.string(),
    passwordPlaceholder: z.string(),
    loginSubmitLabel: z.string(),
    loginSubmittingLabel: z.string(),
    orderPageEyebrow: z.string(),
    orderPaidTitle: z.string(),
    orderClosedTitle: z.string(),
    orderPendingTitle: z.string(),
    orderCourseLabel: z.string(),
    orderNoLabel: z.string(),
    orderPaymentMethodLabel: z.string(),
    orderAmountLabel: z.string(),
    orderPaymentSuffix: z.string(),
    orderPaidRedirectText: z.string(),
    orderClosedHelpText: z.string(),
    orderRepurchaseLabel: z.string(),
    orderScanText: z.string(),
    orderQrAlt: z.string(),
    orderQrLoadingText: z.string(),
    orderRemainingPrefix: z.string(),
    orderCheckingLabel: z.string(),
    orderCheckLabel: z.string(),
    orderFallbackLinkLabel: z.string(),
    orderStatusCheckError: z.string(),
    orderQrLoadError: z.string(),
    myCoursesValidityLabel: z.string(),
    myCoursesLessonCountPrefix: z.string(),
    myCoursesPlayableLessonUnit: z.string(),
    orderExpiresPrefix: z.string(),
    orderExpiredText: z.string(),
  }),
  home: z.object({
    title: z.string(),
    content: z.string(),
    eyebrow: z.string(),
    primaryCtaLabel: z.string(),
    primaryCtaHref: z.string(),
    secondaryCtaLabel: z.string(),
    secondaryCtaHref: z.string(),
    features: z.array(textItemSchema),
    heroImage: z.string(),
    heroImageAlt: z.string(),
    earlyBirdBadgeLabel: z.string(),
    regularPriceBadgeLabel: z.string(),
    audienceLabel: z.string(),
    audienceTitle: z.string(),
    audience: z.string(),
    notAudience: z.string(),
    teacherLabel: z.string(),
    teacherTitle: z.string(),
    teacherIntro: z.string(),
    teacherImage: z.string(),
    teacherImageAlt: z.string(),
    teacherAchievements: z.array(z.string()),
    coursesEyebrow: z.string(),
    coursesTitle: z.string(),
    coursesLinkLabel: z.string(),
  }),
  about: z.object({
    title: z.string(),
    content: z.string(),
    eyebrow: z.string(),
    avatarImage: z.string(),
    avatarAlt: z.string(),
    certificateEyebrow: z.string(),
    certificateTitle: z.string(),
    certificateImage: z.string(),
    certificateAlt: z.string(),
    cards: z.array(textItemSchema),
    achievementsLabel: z.string(),
    achievements: z.array(z.string()),
    serviceLabel: z.string(),
    serviceSteps: z.array(z.string()),
  }),
  courses: z.object({
    eyebrow: z.string(),
    title: z.string(),
    content: z.string(),
    promoEyebrow: z.string(),
    promoTitle: z.string(),
    promoText: z.string(),
    promoServiceText: z.string(),
  }),
  courseDetail: z.object({
    eyebrow: z.string(),
    badges: z.array(z.string()),
    outlineTitle: z.string(),
    emptyLessonSummary: z.string(),
    outcomesTitle: z.string(),
    outcomes: z.array(z.string()),
    audienceTitle: z.string(),
    audience: z.array(z.string()),
    notForTitle: z.string(),
    notFor: z.array(z.string()),
    highlightsTitle: z.string(),
    highlights: z.array(z.string()),
    requirementsTitle: z.string(),
    requirements: z.string(),
    purchaseNotesTitle: z.string(),
    purchaseNotes: z.array(z.string()),
    refundTitle: z.string(),
    refundPolicy: z.string(),
    faqTitle: z.string(),
    faq: z.array(faqItemSchema),
    priceLabel: z.string(),
    regularPriceLabel: z.string(),
    validityPrefix: z.string(),
    lessonCountLabel: z.string(),
    watchMethodLabel: z.string(),
    watchMethod: z.string(),
    serviceModelLabel: z.string(),
    ageRangeLabel: z.string(),
    sidebarNote: z.string(),
  }),
});

export type SiteConfig = z.infer<typeof siteConfigSchema>;

function cloneDefaultConfig(): SiteConfig {
  return siteConfigSchema.parse(DEFAULT_SITE_CONFIG);
}

export async function getSiteSettings(): Promise<SiteConfig> {
  const content = await prisma.siteContent.findUnique({ where: { key: "site-config" } });
  const parsed = siteConfigSchema.safeParse(mergeSiteConfigWithDefaults(cloneDefaultConfig(), content?.metadata));

  return parsed.success ? parsed.data : cloneDefaultConfig();
}

export function getDefaultSiteSettings(): SiteConfig {
  return cloneDefaultConfig();
}
